# Generated by Django 5.0.3 on 2024-04-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_turistusernew_purse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turistusernew',
            name='purse',
        ),
    ]
