# Generated by Django 5.0.3 on 2024-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_order_options_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscket',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
