# Generated by Django 5.0.3 on 2024-04-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_buscket_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buscket',
            name='total_summ',
        ),
    ]
