# Generated by Django 5.0.3 on 2024-04-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_image_remove_buscket_kids_quantity_alter_tour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='kids_price',
        ),
    ]
