# Generated by Django 5.0.3 on 2024-04-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_tour_image_tour_kids_price_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='kids_price',
        ),
    ]
