# Generated by Django 5.0.3 on 2024-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_tour_kids_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(default=True, upload_to='images'),
        ),
    ]
