# Generated by Django 5.0.3 on 2024-04-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_order_amount_order_buscket_order_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.image'),
        ),
    ]
