# Generated by Django 5.0.3 on 2024-04-26 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_tour_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buscket',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment',
        ),
        migrations.AddField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.tour'),
        ),
    ]
