# Generated by Django 5.0.3 on 2024-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_order_buscket_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
