# Generated by Django 5.0.3 on 2024-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_order_date_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='person_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
